### ISSUE TITLE
Error while importing the solution

### ISSUE THREAD

**Issue by RavitejaMuthyala** [a33ik/GoogleAddressAutocomplete_PCF#3] opened 2019-09-05 22:09 UTC
I tried to install your solution into our Dynamics but it errored out. Need some assistance to use this in Dynamics

  | The solution file is invalid. The compressed file must contain the following files at its root: solution.xml, customizations.xml, and [Content_Types].xml. Customization files exported from previous versions of Microsoft Dynamics 365 are not supported.
-- | --

**Comment by onyebuchiboss** [comment] 2019-09-17 22:48
@RavitejaMuthyala u can rebuild it yourself.

**Comment by a33ik** [comment] 2019-09-18 13:51
@RavitejaMuthyala I can't reproduce your issue. What's the version of the instance you try to import solution to? Is it online or on-premise?

**Comment by a33ik** [comment] 2019-09-26 13:13
@RavitejaMuthyala closing the thread.

**Closed by a33ik** 2019-09-26 13:13 UTC

**Comment by RavitejaMuthyala** [comment] 2019-09-26 20:37
@a33ik Version 1710 (9.1.0.8428) online. still won't import directly. Guess will rebuild it myself

**Comment by a33ik** [comment] 2019-09-26 20:41
@RavitejaMuthyala do you download this file - https://github.com/a33ik/GoogleAddressAutocomplete_PCF/releases/download/1.0.0.1/GoogleAddressAutocomplete_1_0_0_1_managed.zip ?

**Comment by RavitejaMuthyala** [comment] 2019-09-26 21:07
this one worked, thank you

**Comment by a33ik** [comment] 2019-09-27 00:27
@RavitejaMuthyala awesome! Glad that it worked!
